name: flutter_roadmap
description: "Flutter Learning Roadmap — Zero to Expert"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_markdown_plus: ^1.0.12
  sqflite: ^2.4.2
  sqflite_common_ffi_web: ^1.0.2
  sqflite_common_ffi: ^2.3.7+1
  path: ^1.9.1
  flutter_riverpod: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/flutter_roadmap.png
    - assets/background_image.png
    - assets/guide_badge.png
    - assets/progress_asset.png
    - assets/progress_bar.png
    - assets/icon_topics.png
    - assets/icon_done.png
    - assets/icon_remaining.png
    - assets/icon_notes.png
